### ISSUE TITLE
Codecube.io is not working

### ISSUE THREAD

**Issue by kablamo** [hmarr/codecube#8]
I'm guessing the Docker daemon is not running?  I don't get back any results when I execute code on the live website.

**Comment by hmarr** [comment]
This has happened once or twice - the docker daemon and the server process are still running, they just don't stream the results to the SSE connection.

It's fixed by restarting the server process, but I'd like to debug it properly and solve this issue once and for all.

An initial glance at the server reveals around 600 TCP connections in CLOSE_WAIT between nginx and the server process. I'll try to have another look into it later today.

**Comment by arikrak** [comment]
This seems to be an issue again. Nothing happens after clicking Run. Chrome shows a timeout error:

> Request URL:http://codecube.io/api/run-snippet/
> Request Method:POST
> Status Code:504 Gateway Time-out

**Comment by hmarr** [comment]
Should be fixed, apologies for the interruption!
